# Generated by Django 2.2.1 on 2019-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
