# Generated by Django 2.2.1 on 2019-05-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.User'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_text',
            field=models.CharField(max_length=200),
        ),
    ]
